name: rsem1.2.25 Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - run: cwl ci
      - run: cwl test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
          registry-url: https://ghcr.io/RaiRuhi/rsem1.2.25/
      - run: cwl ci
      - run: cwl publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
